exclude: "venv|node_modules|.git|env.py"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/myint/eradicate
    rev: v2.0.0
    hooks:
      - id: eradicate
        language_version: python3.10
        entry: eradicate
        files: '\.py$'
        args: [--in-place]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        entry: black --line-length 120 --verbose

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--sl", "--line-length", "120"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["--recursive", "--exclude=tests,venv"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: flake8
        description: "`flake8` is a command-line utility for enforcing style consistency across Python projects."
        entry: flake8
        language: python
        types: [python]
        require_serial: true
        args: ["--config=.flake8"]
        additional_dependencies: [pep8-naming, flake8-blind-except, flake8-bugbear, flake8-comprehensions, flake8-print]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
